# Generated by Django 6.0.4 on 2026-04-13 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('duration_minutes', models.IntegerField(choices=[('1', 'Technical'), ('2', 'Security'), ('3', 'Soft Skills'), ('4', 'Leader Ship'), ('5', 'Product Training'), ('6', 'Cyber Security'), ('7', 'Ethics'), ('8', 'Other')])),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('1', 'IT'), ('2', 'HR'), ('3', 'Sales'), (4, 'Admin'), (5, 'Management')])),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('instructor_name', models.CharField(max_length=150)),
                ('mode', models.CharField(choices=[('1', 'Online'), ('2', 'In-Person')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_portal.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'ENROLLED'), (2, 'COMPLETED'), (3, 'CANCELLED')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='analytics_portal.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='analytics_portal.session')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'session'), name='unique_session')],
            },
        ),
    ]
