# Generated by Django 6.0.4 on 2026-04-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('1', 'Technical'), ('2', 'Security'), ('3', 'Soft Skills'), ('4', 'Leader Ship'), ('5', 'Product Training'), ('6', 'Cyber Security'), ('7', 'Ethics'), ('8', 'Other')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
    ]
